const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const GET_USER_DATA = "GET_USER_DATA";

const SEARCHING = "SEARCHING";
const SEARCH_ERROR = "SEARCH_ERROR";

const SEARCH_MEALS = "SEARCH_MEALS";
const RESET_SEARCH_MEALS = "RESET_SEARCH_MEALS";
const GET_FAV_MEALS = "GET_FAV_MEALS";
const ADD_FAV_MEAL = "ADD_FAV_MEAL";
const REMOVE_FAV_MEAL = "REMOVE_FAV_MEAL";

const FETCHING_INGREDIENTS = "FETCHING_INGREDIENTS";
const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
const GET_INGREDIENTS = "GET_INGREDIENTS";
const SEARCH_INGREDIENTS = "SEARCH_INGREDIENTS";
const RESET_SEARCH_INGREDIENTS = "RESET_SEARCH_INGREDIENTS";
const GET_FAV_INGREDIENTS = "GET_FAV_INGREDIENTS";
const ADD_FAV_INGREDIENT = "ADD_FAV_INGREDIENT";
const REMOVE_FAV_INGREDIENT = "REMOVE_FAV_INGREDIENT";

export {
  AUTH,
  LOGOUT,
  GET_USER_DATA,
  SEARCH_MEALS,
  RESET_SEARCH_MEALS,
  FETCHING_INGREDIENTS,
  FETCH_INGREDIENTS_ERROR,
  GET_INGREDIENTS,
  SEARCH_INGREDIENTS,
  RESET_SEARCH_INGREDIENTS,
  GET_FAV_MEALS,
  GET_FAV_INGREDIENTS,
  ADD_FAV_MEAL,
  ADD_FAV_INGREDIENT,
  REMOVE_FAV_MEAL,
  REMOVE_FAV_INGREDIENT,
  SEARCHING,
  SEARCH_ERROR,
};
