const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const GET_USER_DATA = "GET_USER_DATA";

const SEARCHING = "SEARCHING";
const SEARCH_ERROR = "SEARCH_ERROR";

const FETCHING_MEALS = "FETCHING_MEALS";
const FETCH_MEALS_ERROR = "FETCH_MEALS_ERROR";
const GET_MEALS = "GET_MEALS";
const GET_MEALS_BY_CATEGORY = "GET_MEALS_BY_CATEGORY";
const SEARCH_MEALS = "SEARCH_MEALS";
const RESET_SEARCH_MEALS = "RESET_SEARCH_MEALS";
const GET_FAV_MEALS = "GET_FAV_MEALS";
const ADD_FAV_MEAL = "ADD_FAV_MEAL";
const REMOVE_FAV_MEAL = "REMOVE_FAV_MEAL";

const FETCHING_INGREDIENTS = "FETCHING_INGREDIENTS";
const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
const GET_INGREDIENTS = "GET_INGREDIENTS";
const SEARCH_INGREDIENTS = "SEARCH_INGREDIENTS";
const RESET_SEARCH_INGREDIENTS = "RESET_SEARCH_INGREDIENTS";
const GET_FAV_INGREDIENTS = "GET_FAV_INGREDIENTS";
const ADD_FAV_INGREDIENT = "ADD_FAV_INGREDIENT";
const REMOVE_FAV_INGREDIENT = "REMOVE_FAV_INGREDIENT";

const FETCHING_CATEGORIES = "FETCHING_CATEGORIES";
const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";
const GET_CATEGORIES = "GET_CATEGORIES";

export {
  AUTH,
  LOGOUT,
  GET_USER_DATA,
  FETCHING_MEALS,
  FETCH_MEALS_ERROR,
  GET_MEALS,
  GET_MEALS_BY_CATEGORY,
  SEARCH_MEALS,
  RESET_SEARCH_MEALS,
  FETCHING_INGREDIENTS,
  FETCH_INGREDIENTS_ERROR,
  GET_INGREDIENTS,
  SEARCH_INGREDIENTS,
  RESET_SEARCH_INGREDIENTS,
  FETCHING_CATEGORIES,
  FETCH_CATEGORIES_ERROR,
  GET_CATEGORIES,
  GET_FAV_MEALS,
  GET_FAV_INGREDIENTS,
  ADD_FAV_MEAL,
  ADD_FAV_INGREDIENT,
  REMOVE_FAV_MEAL,
  REMOVE_FAV_INGREDIENT,
  SEARCHING,
  SEARCH_ERROR,
};
