const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const GET_USER_DATA = "GET_USER_DATA";

const FETCHING_MEALS = "FETCHING_MEALS";
const FETCH_MEALS_ERROR = "FETCH_MEALS_ERROR";
const GET_MEALS = "GET_MEALS";
const SEARCH_MEALS = "SEARCH_MEALS";

const FETCHING_INGREDIENTS = "FETCHING_INGREDIENTS";
const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";
const GET_INGREDIENTS = "GET_INGREDIENTS";

const FETCHING_CATEGORIES = "FETCHING_CATEGORIES";
const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";
const GET_CATEGORIES = "GET_CATEGORIES";

export {
  AUTH,
  LOGOUT,
  GET_USER_DATA,
  FETCHING_MEALS,
  FETCH_MEALS_ERROR,
  GET_MEALS,
  SEARCH_MEALS,
  FETCHING_INGREDIENTS,
  FETCH_INGREDIENTS_ERROR,
  GET_INGREDIENTS,
  FETCHING_CATEGORIES,
  FETCH_CATEGORIES_ERROR,
  GET_CATEGORIES,
};
